[project]
name = "spacial-score"
version = "1.1.0"
description = "A Comprehensive Topological Complexity Indicator for Small Molecules"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pytest>=8.4.1",
    "rdkit>=2025.3.5",
]
